#!/bin/sh
export RELEASE="v3.3"
export MIRROR="http://nl.alpinelinux.org/alpine"
export BUILD_OPTIONS="-s -c -t UTC -r $RELEASE -m $MIRROR"
export TAGS="resnullius/alpine:3.3 resnullius/alpine:latest"
export PUSH_IMAGE="true"
