#!/usr/bin/env bash
export RELEASE="v3.3"
export MIRROR="http://nl.alpinelinux.org/alpine"
export PACKAGES="alpine-baselayout,apk-tools,alpine-keys,libc-utils"
export BUILD_OPTIONS=(-b -s -c -t UTC -r $RELEASE -m $MIRROR -p $PACKAGES)
export TAGS=(resnullius/alpine:3.3)
export PUSH_IMAGE="true"
