#!/usr/bin/env bash
export RELEASE="v3.2"
export MIRROR="http://nl.alpinelinux.org/alpine"
export BUILD_OPTIONS="-s -E -c -t UTC -r $RELEASE -m $MIRROR"
export TAGS="resnullius/alpine:3.2"
export PUSH_IMAGE="true"
